### PR TITLE
Improve force redisplay advice

### LINKED ISSUE #34: Truncated org-attach popup
Maybe related to the `org-set-tags-command` case but worse and doesn't get fixed with the previous redisplay.

I've seen this in both moody and doom modelines.

Also disabled the redisplay advice just in case but to no avail.

Recipe:

1. Open any org file
2. Press `C-c C-a`
3.  You should see something like:

image

instead of (without customized modeline):

image

### PR DESCRIPTION
**Pull request by memeplex**
Fix #34

By unconditionally advising `split-window` we ensure that redisplay:

1. Always triggers in the right window, so it solves an issue with `org-attach` calling `fit-window-to-buffer` from a different window.

2. It's not tied to a buffer that may outlive its popup, so it solves the issue with `org-set-tags-command` which buffer kept lurking around with `moody--size-hacked-p` set to t.

As all known workarounds, this will trigger a quick sequence redisplay -> fit -> redisplay that causes some little flickering when the window effectively changes size in-between (which is usually the case with popups).

Moreover, `fit-window-to-buffer` always transforms a height in pixels to a height in characters and this operation unavoidably rounds up to the next integer height in characters when the mode-line is of a different size than the default character, hence introducing some small amount of padding at the bottom of the window.

In order to avoid small but yet unpleasant visual artifacts whenever possible, we only trigger a redisplay when it is strictly required, that is when the mode-line height effectively differs from the default character height.

### CODE REVIEW

**Comment by memeplex** [comment]
> In order to avoid small but yet unpleasant visual artifacts whenever possible, we only trigger a redisplay when it is strictly required, that is when the mode-line height effectively differs from the default character height.

@tarsius the clause

```elisp
  (unless (cl-evenp height)
    (cl-incf height))
```

makes setting a vanilla-height modeline more difficult than it could have been. Do you think that it can be relaxed to allow non even heights without too much hassle?

**Comment by memeplex** [comment]
Moreover, if you prefer to keep the version that only triggers redisplays on fits I guess that it can be arranged by:

1. Using a window parameter in place of a buffer local variable.
2. Inspecting the `window` argument of `fit-window-to-buffer` and running the redisplay in the target window.

Nevertheless it's still a piecemeal approach and, for whatever reasons, doom-modeline is already advising `resize-temp-buffer-window` besides `fit-window-to-buffer`, I'm afraid that you will be always playing catch up with new problematic cases.

I don't think it's worth the trouble.

**Comment by tarsius** [comment]
Thanks for working on this!

Mentioning https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38181 so that I can go directly there instead of having to look at other related issues until I find one that contains that link. :grinning:

I'll delay merging until the discussion there settles down.

**Comment by memeplex** [comment]
I will be testing it more thoroughly this weekend, but I don't expect the patch to arrive in emacs-28. Even if it arrived people with previous versions would still be having popup issues. I agree that it's better to be cautious with regard to the changes proposed here, but what do you think about https://github.com/tarsius/moody/pull/35#issuecomment-945022946? For some time the safer choice (no cropping, no flickering, no other problem we already don't know about) would likely be to have a standard sized modeline. Aesthetically I don't think it harms moody at all, but I haven't carefully looked at the involved calculations and I don't how much complex would they be by allowing odd pixel heights.

**Comment by tarsius** [comment]
I've pushed a fixup commit. Please have a look.

**Comment by memeplex** [comment]
I think all your changes are for the best.

```elisp
setq height (or moody-mode-line-height (window-mode-line-height))))
```

won't actually honor `window-mode-line-height` if it's odd but you already know that and it's better than nothing.

**Comment by tarsius** [comment]
I am not sure how to parse that sentence. Are you saying that if `window-mode-line-height` is odd then that value isn't honored? Or that `window-mode-line-height` may be odd and we then use that even though that's not optimal?

**Comment by memeplex** [comment]
No, just what we have talked some days ago, that afterwards it will be changed to make it even, so ultimately modeline height != char height in those cases, except that you have changed something else or I'm wrong.

**Comment by memeplex** [comment]
I mean, all this is relevant wrt the upstream bug, not that 1 px less or more matters otherwise.

**Comment by tarsius** [comment]
Tadaa :grinning: 

Thanks for all your work on this!

**Comment by memeplex** [comment]
:) thanks.

**Comment by tarsius** [comment]
Aaargl. I messed it up while testing and then committing a change that was only intended for testing. I pushed a fix.

**Pull request merged**
